const objects = [
    {   
        id: 1,
        width: 160,
        height: 40,
        xpos: 50,
        ypos: 50,
        color: "blue",
    },
    {   
        id: 2,
        width: 160,
        height: 40,
        xpos: 50,
        ypos: 130,
        color: "blue",
    },
    {   
        id: 3,
        width: 160,
        height: 40,
        xpos: 50,
        ypos: 210,
        color: "blue",
    },
    {   
        id: 4,
        width: 160,
        height: 40,
        xpos: 50,
        ypos: 290,
        color: "blue",
    },
    {   
        id: 5,
        width: 160,
        height: 40,
        xpos: 50,
        ypos: 370,
        color: "blue",
    },
    {   
        id: 6,
        width: 160,
        height: 40,
        xpos: 250,
        ypos: 50,
        color: "blue",
    },
    {   
        id: 7,
        width: 160,
        height: 40,
        xpos: 250,
        ypos: 130,
        color: "blue",
    },
    {   
        id: 8,
        width: 160,
        height: 40,
        xpos: 250,
        ypos: 210,
        color: "blue",
    },
    {   
        id: 9,
        width: 160,
        height: 40,
        xpos: 250,
        ypos: 290,
        color: "blue",
    },
    {   
        id: 10,
        width: 160,
        height: 40,
        xpos: 250,
        ypos: 370,
        color: "blue",
    },
]

export default objects